name: QA Tests CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
        
      - name: Instalar dependências
        run: npm install

      # ---------------------- Cypress ----------------------

      - name: Rodar Cypress 
        uses: cypress-io/github-action@v6
        with:
          install: true

          runTests: true

        env:
          CYPRESS_API_KEY: ${{ secrets.API_KEY }}

      # ---------------------- Postman ----------------------

      - name: Instalar Newman
        run: npm install -g newman

      - name: Rodar coleção Postman
        run: |
          newman run postman_collection.json \
          -e postman_environment.json \
          --env-var "api_key=${{ secrets.API_KEY }}"

